# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e94b71314673742a3c0d35ef0a0dee5f420797233ccf3df235272efad5e43673d7c9281eef5c6dcc98afe4dbddf7b087ecf65c4d52be335729bdd9217e6cc936

test:
  secret_key_base: f2b85ef44a8540b23cb83e41c74f647abe85d48b1d6c6ec22894a53a5dd36265bfe8f01456616b02b91d005de86206339802269b3164c8a35325289780a37f01

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
